import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface OrderItem {
  item: string;
  quantity: number;
  price: number;
}

interface NewOrderPayload {
  customer_name: string;
  phone_number: string;
  subtotal?: number;
  subtotal_with_tax?: number;
  items: OrderItem[];
  // order_id and customer_id are NOW AUTO-GENERATED, so NOT required in payload
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    const payload: NewOrderPayload = await req.json();
    
    console.log('Received new order:', payload);

    // Validate required fields (customer_id and order_id NO LONGER required)
    if (!payload.customer_name || !payload.phone_number) {
      console.error('Missing required fields in payload');
      return new Response(
        JSON.stringify({ error: 'Missing required fields: customer_name and phone_number are required' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Calculate subtotal if not provided
    let subtotal = payload.subtotal || 0;
    if (!payload.subtotal && payload.items && payload.items.length > 0) {
      subtotal = payload.items.reduce((sum, item) => sum + (item.price * item.quantity), 0);
    }

    // Calculate subtotal_with_tax if not provided (Quebec tax: 14.975%)
    const subtotal_with_tax = payload.subtotal_with_tax || (subtotal * 1.14975);

    // Insert order WITHOUT order_id or customer_id
    // The trigger will auto-generate them
    const { data: orderData, error: orderError } = await supabase
      .from('orders')
      .insert({
        // order_id: AUTO-GENERATED by trigger
        // customer_id: AUTO-GENERATED by trigger (or fetched if customer exists)
        customer_name: payload.customer_name,
        phone_number: payload.phone_number,
        subtotal: subtotal,
        subtotal_with_tax: subtotal_with_tax,
        status: 'new',
        new_order_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (orderError) {
      console.error('Error inserting order:', orderError);
      return new Response(
        JSON.stringify({ error: 'Failed to create order', details: orderError.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Order created:', orderData);

    // Insert order items if provided
    if (payload.items && payload.items.length > 0) {
      const orderItems = payload.items.map((item) => ({
        order_id: orderData.order_id, // Use the auto-generated order_id
        item: item.item,
        quantity: item.quantity,
        price: item.price,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) {
        console.error('Error inserting order items:', itemsError);
        // Order was created but items failed - log but don't fail the request
      } else {
        console.log('Order items created:', orderItems.length);
      }
    }

    return new Response(
      JSON.stringify({ 
        success: true, 
        message: 'Order created successfully',
        order_id: orderData.order_id, // Return the auto-generated order_id
        customer_id: orderData.customer_id, // Return the auto-generated or fetched customer_id
        subtotal: subtotal,
        subtotal_with_tax: subtotal_with_tax
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Unexpected error:', error);
    return new Response(
      JSON.stringify({ error: 'Internal server error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});